env:
  - name: LOG_PATH
    value: "/var/log/app/application.log"
  - name: LOG_LEVEL
    value: "info"

replicaCount: 4

image:
  repository: "angelvs/go-api"
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 8080

resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "250m"
    memory: "128Mi"

imagePullSecrets:
  name: docker-hub-secret

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: true
  accessMode: ReadWriteMany
  size: 1Gi
  storageClass: ""
  path: "/data/logs"